name: ci

on:
  pull_request:
    branches:
      - trunk

env:
  ZIG_VERSION: "0.14.0"

jobs:
  build:
    strategy:
      matrix:
        repo:
          - shaderc
    runs-on: ubuntu-latest
    steps:
    - name: Setup Zig
      uses: mlugg/setup-zig@v1
      with:
        version: ${{ env.ZIG_VERSION }}

    - uses: actions/checkout@v4
      with:
        repository: "${{ github.repository_owner }}/${{ matrix.repo }}.zig"

    - name: Prepare ${{ matrix.repo }}.zig/build.zig.zon
      env:
        SHA: "${{ github.event.pull_request.head.sha }}"
        URL: "${{ github.server_url }}/${{ github.repository }}/archive"
      shell: 'bash'
      run: |
        old_url="$(grep -o "${URL}/.*\.tar\.gz" build.zig.zon)"
        old_hash="$(zig fetch "${old_url}")"
        new_url="${URL}/${SHA}.tar.gz"
        new_hash="$(zig fetch "${new_url}")"
        sed -i "s@${old_url}@${new_url}@;s@${old_hash}@${new_hash}@" build.zig.zon

    - name: Test updating ${{ matrix.repo }}.zig
      env:
        REPO: "${{ matrix.repo }}"
        RUNNER_TMP: "${{ runner.temp }}"
      shell: 'bash'
      run: |
        case "${REPO}" in
        ( * ) zig build -Dupdate ;;
        esac

    - name: Test fetching ${{ matrix.repo }}.zig
      env:
        REPO: "${{ matrix.repo }}"
        RUNNER_TMP: "${{ runner.temp }}"
      shell: 'bash'
      run: |
        case "${REPO}" in
        ( * ) zig build -Dfetch ;;
        esac
