name: cd ping

on:
  push:
    tags:
      - '*'

env:
  ZIG_VERSION: "0.14.0"

jobs:
  ping:
    permissions:
      contents: write
    strategy:
      matrix:
        repo:
          - shaderc
    runs-on: ubuntu-latest
    steps:
    - uses: mlugg/setup-zig@v1
      with:
        version: ${{ env.ZIG_VERSION }}

    - name: Notify ${{ matrix.repo }}.zig
      env:
        ENDPOINT: "/repos/${{ github.repository_owner }}/${{ matrix.repo }}.zig/dispatches"
        EVENT_TYPE: "event_type=ping-from-${{ github.event.repository.name }}"
        GH_TOKEN: "${{ secrets.PAT }}"
        PAYLOAD_FROM: "client_payload[from]=${{ github.event.repository.name }}"
        PAYLOAD_TAG: "client_payload[tag]=${{ github.ref_name }}"
        URL: "${{ github.server_url }}/${{ github.repository_owner }}/${{ github.event.repository.name }}/archive/refs/tags/${{ github.ref_name }}.tar.gz"
      shell: 'bash'
      run: |
        payload_hash="client_payload[hash]=$(zig fetch "${URL}")"
        gh api --method POST \
          -H 'Accept: application/vnd.github+json' \
          -H 'X-GitHub-Api-Version: 2022-11-28' \
          -f "${EVENT_TYPE}" \
          -F "${PAYLOAD_FROM}" -F "${PAYLOAD_TAG}" -F "${payload_hash}" \
          "${ENDPOINT}"
